### ISSUE TITLE
Invite first 100 users

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#465]
### Invite first 100 users.

- [ ] Implement vue-tour https://github.com/anthive/website/issues/467
- [ ] Notifications (Web) https://github.com/anthive/website/issues/468
- [ ] Round robin https://github.com/anthive/website/issues/469
- [ ] Emails https://github.com/anthive/website/issues/470
- [ ] Fix rust https://github.com/anthive/website/issues/471
- [ ] ToS and PP page https://github.com/anthive/website/issues/472
- [ ] Update rules page https://github.com/anthive/website/issues/473
- [ ] Register 5 account with good bots page https://github.com/anthive/website/issues/474
- [ ] Update Sample bots names and photos https://github.com/anthive/website/issues/476
- [ ] Filters on Games page https://github.com/anthive/website/issues/475
- [ ] Video tutorial https://github.com/anthive/website/issues/477
- [ ] Alert what just happened https://github.com/anthive/website/issues/478

**Comment by kezlya** [comment]
Obsolete. Moved to board
